### PR TITLE
Alias Raven.send to Rave.send_object_message

### PR DESCRIPTION
**Pull request by mattwalters**

### CODE REVIEW

**Comment by nateberkopec** [comment]
*headdesk*. Yeah, we probably shouldn't be overriding send.

**Comment by mattwalters** [comment]
Yeah, probably not. I'm happy to just rename the method as well. Although, I'm not sure if you want to do that since it is likely to break existing implementations.

**Comment by nateberkopec** [comment]
Yeah. A lot of people are using Raven.send in their job processors are well. We'll definitely need a deprecation cycle.

**Comment by nateberkopec** [comment]
Closing in favor of #326 for now. Thanks for pointing this out.

**Pull request closed without merging**
