### PR TITLE
Modified the client send to accept both a Raven::Event and an already serialized "to_hash" event.

### PR DESCRIPTION
**Pull request by marclennox**
Addresses issue #282

### CODE REVIEW

**Comment by nateberkopec** [comment]
I like the principle, but not psyched about `is_a?`. Is there any way we can do this with some more Rubylike duck-typing?

**Comment by marclennox** [comment]
I'll resubmit in a bit

—

**Comment by marclennox** [comment]
I’ve rebased and re-pushed the commit.


—

**Comment by marclennox** [comment]
I fixed a few issues with this PR, rebased and re-pushed.  Do you need anything else to accept it?

**Comment by nateberkopec** [comment]
Yeah, I'm still not stoked about the code (respond_to? is still a bandaid IMO), but there's not really a fix for that without getting kind of crazy. 

That said, how about a test for sending a Hash?

**Comment by nateberkopec** [comment]
@marclennox Also, I'll merge without this, but two suggestions for alternative implementations (again, if you just give me a test, I can do these things myself, so NBD):

* The #send method should try to convert whatever it receives into a Hash
* The caller of #send (Raven::Base I think?) should be responsible for calling #send with a Hash argument, and #send should assume that it's called with a hash-like object.

**Comment by marclennox** [comment]
Thanks @nateberkopec, would you suggest I add a test to raven_spec.rb?

**Comment by marclennox** [comment]
Also one thing to note, I didn't have to make any change to the send method because a hash responds to to_hash and returns itself.

**Comment by nateberkopec** [comment]
@marclennox Yeah thats fine

**Comment by marclennox** [comment]
This pull request is replaced by https://github.com/getsentry/raven-ruby/pull/300.

**Pull request closed without merging**
