### PR TITLE
Warn dont error 4xx

### PR DESCRIPTION
**Pull request by iloveitaly**
#644 has all of the relevant documentation.

### CODE REVIEW

**Comment by iloveitaly** [comment]
@HazAT any interest in merging this in? I can rebase on master and re-push—let me know!

**Comment by HazAT** [comment]
Yeah, if you go ahead and rebase it I can merge it :)

**Comment by iloveitaly** [comment]
@HazAT rebased!

**Comment by HazAT** [comment]
`2.11.2` released!

**Pull request merged**
