### PR TITLE
WIP: Fix Rails multi-exception reports

### PR DESCRIPTION
**Pull request by nateberkopec**

### CODE REVIEW

**Comment by nateberkopec** [comment]
ping @mattrobenolt 

This fixes the issue for the app you provided in #388, and, as far as I can tell, doesn't break any additional use cases. Can you take a look?

**Comment by nateberkopec** [comment]
Can also confirm this works correctly with `rescue_from` - errors which are not re-raised by `rescue_from` are not reported.

**Comment by greysteil** [comment]
:+1: :heart:

**Comment by mattrobenolt** [comment]
I tested this locally, and it seems to record the wrong one now.

It only logged one event, but it only logged the event wiht the url of `/500`, not the original url. So seems like we're filtering out the wrong one.

**Comment by mattrobenolt** [comment]
For posterity, I ran against my docker container:

```
$ docker run --rm --name=sentry-test -e RAILS_ENV=production -e SENTRY_DSN=https://xxx:xxx@app.getsentry.com/3825 -p 3000:3000 -v $PWD:/usr/src/app -v /Users/matt/code/getsentry/raven-ruby:/usr/local/bundle/gems/sentry-raven-0.15.2 -it sentry-test
```

And mounted in this PR.

Without mounting this in, it was recording the error twice. Now only records once, but the wrong one.

**Comment by nateberkopec** [comment]
For posterity: I worked this out with @mattrobenolt and made sure the right exception was recorded.

**Pull request merged**
