### PR TITLE
Add ActionController::UnknownFormat to ignore exceptions

### PR DESCRIPTION
**Pull request by iguchi1124**
ActionController::UnknownFormat is rescued 406 http response from rails 5.

https://github.com/rails/rails/issues/20666

so, I added this exception to default ignore exceptions. what do you think?  @nateberkopec

### CODE REVIEW

**Comment by nateberkopec** [comment]
Hmmm... sometimes I like receiving these because they're usually bad bots that I want to block. I guess I'm not sure.

**Comment by iguchi1124** [comment]
I don't want to notify this error because this is not a server error. 
It has better to make configure in the application's `Rave.config.excluded_exceptions` if someone want to notify this error for security reasons.

I think this proposal is same as ignoring `ActionController::InvalidAuthenticityToken`. 💭

**Comment by nateberkopec** [comment]
Closing in favor of #769, but thanks for opening (otherwise wouldn't have had the idea!)

**Comment by iguchi1124** [comment]
thanks!

**Pull request closed without merging**
