### PR TITLE
Fix user_context to merge with existing context

### PR DESCRIPTION
**Pull request by meganemura**

### CODE REVIEW

**Comment by meganemura** [comment]
Test is failing due to #890

**Comment by st0012** [comment]
thanks for the PR, but I don't see a clear reason for this change. can you give me an example or related issue report?

**Comment by st0012** [comment]
I'm closing this now, but feel free to reopen it if you still think it's needed.

**Comment by agrobbin** [comment]
@st0012 I believe this is still a bug, or at least an inconsistency with the documentation on `user_context`. It states:

```
# Bind user context. Merges with existing context (if any).
```

However, the actual implementation appears to overwrite anything that's already set within `user_context`. For example:

```ruby
Raven.user_context(id: current_user.id))
Raven.user_context(email: current_user.email) if current_user.email
```

This will result in the `user_context` losing the `:id` info if `current_user.email` is truthy.

**Comment by st0012** [comment]
@agrobbin thanks for raising this again with examples 👍  I've added https://github.com/getsentry/sentry-ruby/pull/1064 to address that.

**Comment by agrobbin** [comment]
No problem @st0012, and thanks for the quick fix!!

**Pull request closed without merging**
