### PR TITLE
Switch to built-in JSON module

### PR DESCRIPTION
**Pull request by dcramer**
Refs GH-480, GH-481

### CODE REVIEW

**Comment by dcramer** [comment]
If circular references are indeed an issue we need to be concerned about we can whip up some tests and a quick solution. I'm not sure if the cost is too high to always attempt to remove them before encoding, or if theres a better way to do it with JSON.

**Comment by seanlinsley** [comment]
Huh... I could've sworn there was a test for circular references back when I worked on #166.

Looks like the original PR adding OkJSON (#118) did indeed add a test.

#223 moved it to [(implementation)](https://github.com/getsentry/raven-ruby/blob/944e72b67b3e/lib/raven/processor/removecircularreferences.rb) & [(spec)](https://github.com/getsentry/raven-ruby/blob/944e72b67b3e/spec/raven/processors/removecirculareferences_spec.rb)

**Comment by seanlinsley** [comment]
Since the test is still around, I'd say :shipit:

**Comment by mdayaram** [comment]
Cool! Are we good to go with this? Would love to see this in the main gem, we've been working off a fork in the interim that uses the native JSON module instead.

**Comment by dcramer** [comment]
I'll defer to @seanlinsley and @nateberkopec if they think this is mergable

**Comment by dcramer** [comment]
But since @seanlinsley suggests so, lets do it!

**Comment by mdayaram** [comment]
\o/ woo! Do we have any idea when the next release that includes this change be?

**Comment by seanlinsley** [comment]
🎉 🍻 It's great that we're finally relying on the built-in JSON library

**Pull request merged**
