### PR TITLE
Fix #967: 'can't modify frozen String' error on Rails 5.2 and ruby 2.7.1'

### LINKED ISSUE #967: can't modify frozen String on Rails 5.2 and Ruby 2.7
What I did:
- add sentry to a rails 5.0 app (this fork to be exact: https://github.com/eirvandelden/cityofbrass)
- update to ruby 2.7.1
- update to rails 5.2
- start rails server

What I expected: 
- a working app

What I got:
- `can't modify frozen String: "https://sentry.io", created at /Users/eirvandelden/.gem/ruby/2.7.1/gems/sentry-raven-2.13.0/lib/raven/configuration.rb:255 (FrozenError)`

What I did to fix this locally:
in `lib/raven/configuration.rb` change `@server = "#{scheme}://#{host}"` to `@server = "#{scheme}://#{host}".dup`

full backtrace:
```
🚀 RUBYOPT="--enable-frozen-string-literal --debug=frozen-string-literal" rails s
/Users/eirvandelden/.gem/ruby/2.7.1/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
Traceback (most recent call last):
	32: from /Users/eirvandelden/Sites/cityofbrass/.git/safe/../../bin/rails:6:in `<main>'
	31: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
	30: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	29: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
	28: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	27: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	26: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	25: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	24: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	23: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<main>'
	22: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/railties-5.2.4.3/lib/rails/command.rb:46:in `invoke'
	21: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/railties-5.2.4.3/lib/rails/command/base.rb:69:in `perform'
	20: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	19: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	18: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	17: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/railties-5.2.4.3/lib/rails/commands/server/server_command.rb:142:in `perform'
	16: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/railties-5.2.4.3/lib/rails/commands/server/server_command.rb:142:in `tap'
	15: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/railties-5.2.4.3/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	14: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
	13: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	12: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
	11: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	10: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 9: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 8: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 7: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 6: from /Users/eirvandelden/Sites/cityofbrass/config/application.rb:11:in `<main>'
	 5: from /Users/eirvandelden/Sites/cityofbrass/config/application.rb:13:in `<module:Brasscore>'
	 4: from /Users/eirvandelden/Sites/cityofbrass/config/application.rb:41:in `<class:Application>'
	 3: from /Users/eirvandelden/.rubies/ruby-2.7.1/lib/ruby/2.7.0/forwardable.rb:235:in `configure'
	 2: from /Users/eirvandelden/.gem/ruby/2.7.1/gems/sentry-raven-2.13.0/lib/raven/instance.rb:68:in `configure'
	 1: from /Users/eirvandelden/Sites/cityofbrass/config/application.rb:42:in `block in <class:Application>'
/Users/eirvandelden/.gem/ruby/2.7.1/gems/sentry-raven-2.13.0/lib/raven/configuration.rb:257:in `server=': can't modify frozen String: "https://sentry.io", created at /Users/eirvandelden/.gem/ruby/2.7.1/gems/sentry-raven-2.13.0/lib/raven/configuration.rb:255 (FrozenError)
```

### PR DESCRIPTION
**Pull request by eirvandelden**
This is the change I made locally to fix the FrozenError exception as I encountered it in #967

### CODE REVIEW

**Comment by st0012** [comment]
@eirvandelden thanks for the work! I have fixed the CI build btw, can you rebase the latest master and push again?

**Comment by eirvandelden** [comment]
﻿Thanks for fixing CI, I’ll rebase the branch tomorrow 👍🏼

Groetjes,
Etienne



Groetjes,
Etienne

**Comment by eirvandelden** [comment]
@st0012 I've rebased and all test pass 👍

**Comment by st0012** [comment]
@eirvandelden after digging into the issue, I think a more thorough solution is to avoid using string mutation methods (`<<`) and just use string concatenation. I also added a test suite with `--enable-frozen-string-literal` option enabled. 

the above changes are made in https://github.com/getsentry/raven-ruby/pull/977. so I will close this one after merging it. thanks again for reporting the issue and sorry for not asking to rebase before giving it a closer look 😢

**Comment by eirvandelden** [comment]
That's okay, I thought about rewriting the code to no longer using string mutation, but opted not to, because I'm unfamiliar with the code base. I'm glad you took the effort to do it 👍

**Pull request closed without merging**
