### PR TITLE
Add PostData and Cookies processors by default

### LINKED ISSUE #252: Client should not send form POST data by default
See [spec](http://sentry.readthedocs.org/en/latest/developer/client/index.html#client-usage-end-user).

Also verify we're not sending cookie data by default.

### PR DESCRIPTION
**Pull request by nateberkopec**
Would close #252 and #445.

### CODE REVIEW

**Comment by nateberkopec** [comment]
https://docs.getsentry.com/hosted/clientdev/

> Feature based support is required for the following:

> If cookie data is available, it’s not sent by default
> If POST data is available, it’s not sent by default

**Comment by nateberkopec** [comment]
Blocked on decision at https://github.com/getsentry/sentry-docs/pull/30

**Comment by dcramer** [comment]
I think I'd prefer this change. When I added the bit to the docs it was more of "this is how things should work" vs "this is how SDKs are currently implemented".

**Comment by seanlinsley** [comment]
If this ends up being merged, it seems like y'all should notify all Ruby users on Sentry of this change. I'd certainly want to know, instead of wondering why events stopped having potentially vital information to identify the problem.

**Comment by nateberkopec** [comment]
@seanlinsley :+1: and agree

**Comment by seanlinsley** [comment]
What's the versioning policy? I'd consider this (and potentially dropping OkJSON in #480) as worthy of a major version bump.

**Comment by nateberkopec** [comment]
We're still "unstable", so 0.x.0 releases may still contain breaking changes. I try to keep them out of 0.0.x releases.

**Pull request merged**
