### PR TITLE
Fix crash when Process.wait is used

### PR DESCRIPTION
**Pull request by asBrettisay**
Make `sys_command` tolerate a missing $CHILD_STATUS.

Hi 👋 in my code I was using `Process.wait` and found that it was causing this error in sentry-raven: `undefined method `exitstatus' for nil:NilClass`

My understanding is that calling `Process.wait` clears out the ruby global for last child process, and this is causing the error. I think that sentry-raven should be able to work if I use `Process.wait` or something similar like `trap('CLD', 'IGNORE') so I made a PR that I think will fix the issue. Hope that this helps 👍.

### CODE REVIEW

**Comment by dennis-ef** [comment]
Can this please be implemented. It's also fixing crashes for me. It was difficult to figure out what was the problem until I found this PR. Thank you.

**Comment by asBrettisay** [comment]
@HazAT can we see if this will work?

**Comment by HazAT** [comment]
Oh, @asBrettisay Can you please fix the tests before merging? 
Thx

**Comment by asBrettisay** [comment]
@HazAT Will do

**Comment by asBrettisay** [comment]
@HazAT Tests are passing

**Pull request merged**
