### PR TITLE
Avoid failure log message if not git repository

### PR DESCRIPTION
**Pull request by nateberkopec**
#438

### CODE REVIEW

**Comment by yuku-t** [comment]
:+1: 

I really need this change. Because I use crontab's email forwarding feature, whenever a cron task starts a Rails server, I receive a mail with the git error message. :expressionless:

**Comment by nateberkopec** [comment]
I'm not sure I got the `File.directory` call right here, need to test this.

**Comment by yuku-t** [comment]
Checking the existence of ".git" directory makes sense as long as current working directory is the root of a git repository. `git` commands can be used in subdirectories so this patch is not perfect, but I think it's probably sufficient.

As I wrote in #444, redirection is another choice. I checked it works as expected in Linux (*NIX) machine. The problem is that I'm not sure whether it works in Windows.

**Comment by nateberkopec** [comment]
:+1: looks like this works

**Comment by nateberkopec** [comment]
Pushing a teeny release soon

**Comment by dex1t** [comment]
:+1:

**Comment by michaelsauter** [comment]
@nateberkopec Any news on that release? Holding off upgrading from 0.15.2 at the moment.

**Comment by dosire** [comment]
@nateberkopec We would also love to see that release. GitLab users are confused by the message https://gitlab.com/gitlab-org/gitlab-ce/issues/12657

**Comment by nateberkopec** [comment]
Fixed in 0.15.4, released.

**Comment by michaelsauter** [comment]
Thanks!

**Pull request merged**
