### PR TITLE
Fallback to sync sending if async fails

### PR DESCRIPTION
**Pull request by nateberkopec**
Note this won't catch exceptions in threads, obviously.

See also #511 and #506

---
This change is [Reviewable](https://reviewable.io/reviews/getsentry/raven-ruby/548)

### CODE REVIEW

**Comment by nateberkopec** [comment]
Anyone know of any jiu-jitsu I can do if someone is using a Thread that raises an exception?

**Comment by nuclearpidgeon** [comment]
You could perhaps wrap the exception handling code in a lambda/block, and pass that as another argument to the `config.async` lambda/block - but it's pretty superfluous at that point as that handler would just call 'send_event' anyway.. which presumably would have just failed for some reason. Unless you want to just pass in the Logger call.

Also just a heads up, that [config.rst page doesn't seem to render properly in GitHub](https://github.com/nateberkopec/raven-ruby/blob/2f67d78722db5fe19782d0a745878e3249e695d3/docs/config.rst). Not sure if this is just a GitHub problem or some kind of syntax error

**Comment by nateberkopec** [comment]
Hmm. [We could `call` the `transport_failure_callback`.](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/configuration.rb#L139). Normally that's called when there's a 500 error from Sentry, but it might be appropriate here too.

**Comment by dcramer** [comment]
Of note 429 and 403 codes, for example, should not be retried. So as long as it's only 500 it might be ok. That's still not great behavior though as it means sdks could hammer sentry in certain situations.

**Comment by nateberkopec** [comment]
Actually, `send_event` will just call `transport_failure_callback` anyway if Sentry returns an error. I think a loud (error-level) log message is probably enough here.

**Pull request merged**
