### PR TITLE
Remove unused private Base method.

### PR DESCRIPTION
**Pull request by phillbaker**
* Missed cleanup from dbb290e.
* Also fills in pending specs for Raven::Instance#context

### CODE REVIEW

**Comment by phillbaker** [comment]
Hm, I don't get these rubocop errors locally, any idea how to reproduce?

**Comment by nateberkopec** [comment]
@phillbaker Sorry about that. Please rebase against master and `bundle update`.

**Comment by phillbaker** [comment]
@nateberkopec thanks for taking a look - after rebasing, it looks like the 1.9 builds are failing with `rest-client requires Ruby version >= 2.0.0`

**Comment by nateberkopec** [comment]
@phillbaker Fixed. Rebase again, plz.

**Comment by nateberkopec** [comment]
Nvm, did it myself

**Comment by phillbaker** [comment]
Thanks! Cheers

**Pull request merged**
