### PR TITLE
Allow fixnums as hash key

### PR DESCRIPTION
**Pull request by michaelsauter**
I got the error "Hash key is not a string" for a number in one of my apps during encoding of the data to be sent. I am not entirely sure where it came from since I wasn't able to reproduce that problem locally. My current assumption is that it was some key set during `Raven.user_context`.

While it could be said that the application is to blame for this, I think Sentry should be more forgiving. After all, Sentry is meant to collect errors, not produce any :) Sentry should do whatever it can to report errors in my application, no matter what is being thrown at it. In that light, I wonder whether "okjson" is the right way to do JSON encoding at all. From their repo:

> Note for people who've used other ruby json
libraries: json does not represent symbols,
so okjson does not encode them. It won't
convert them to strings; that would silently
corrupt your data. The same holds for all of
ruby's other data types that don't exist in
json, including Range, Regexp, Proc, Time,
and user-defined classes.

Sentry should not be concerned with "corrupting data". Already Sentry is handling symbols in the vendored version since this is so common in Ruby. I think you're going to fight "upstream" okjson quite a bit going forward ...

### CODE REVIEW

**Comment by nateberkopec** [comment]
Yeah, we've fought JSON before - unfortunately using something like multi_json or even just the built-in JSON causes us more problems for the reasons you describe - we need to be more forgiving. At least with OKJSON we have a recourse (modifying the implementation).

**Comment by nateberkopec** [comment]
@michaelsauter Can you add a test for this? I'm 70% sure I'm OK with this but it will need a test.

**Comment by michaelsauter** [comment]
@nateberkopec Thanks for commenting so quickly. I can look into that, but won't get to it until next week. Will update on Monday.

**Comment by michaelsauter** [comment]
@nateberkopec Added some tests. Thought I'd restructure the original test a bit so it is easier to extend it with other types if there's a need to add more later.

**Comment by nateberkopec** [comment]
Oh neat, I like the additions. Thank you!

**Pull request merged**
