### PR TITLE
Allow some fields to be excluded from sanitization

### PR DESCRIPTION
**Pull request by rclavel**
That's a feature we need for our project.
In our project, I have monkey-patch `Configuration` and created a new processor, but I think this option could be in the original processor.

### CODE REVIEW

**Comment by nateberkopec** [comment]
We already skip frozen values, so I'm not sure what the use case is for this patch. Can you explain your use?

**Comment by rclavel** [comment]
I have a field with `authorization` in its name, and I don't want it to be sanitized.
For this use case, do you freeze explicitly the value?
It seems better for me to put the list of excluded values in the initializer, where all the configuration is set.

**Comment by nateberkopec** [comment]
@mattrobenolt even if I don't sanitize such a field, won't the upstream Sentry server sanitize it anyway?

**Comment by rclavel** [comment]
@nateberkopec It will, but there is a setting on admin view to exclude some fields from sanitization.

**Pull request closed without merging**
